# Generated by Django 4.2.6 on 2023-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_bestyrelse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestyrelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=255)),
                ('mellemnavn', models.CharField(blank=True, max_length=255, null=True)),
                ('efternavn', models.CharField(max_length=255)),
                ('alder', models.CharField(max_length=255)),
                ('funktion', models.CharField(max_length=255)),
                ('band_dk', models.CharField(max_length=255)),
                ('band_int', models.CharField(max_length=255)),
                ('civilstatus', models.CharField(max_length=255)),
                ('fun_fact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Bestyrelsen',
            },
        ),
    ]
