# Generated by Django 4.2.6 on 2023-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestyrelse',
            name='alder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestyrelse',
            name='band_dk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestyrelse',
            name='band_int',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestyrelse',
            name='civilstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestyrelse',
            name='fun_fact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bestyrelse',
            name='funktion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
