# Generated by Django 4.2.6 on 2023-10-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_bestyrelse_alder_alter_bestyrelse_band_dk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spillested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('postnr', models.CharField(max_length=4)),
                ('by', models.CharField(max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('hjemmeside', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Spillesteder',
            },
        ),
        migrations.AlterModelOptions(
            name='bestyrelse',
            options={'ordering': ['fornavn'], 'verbose_name_plural': 'Bestyrelsen'},
        ),
        migrations.CreateModel(
            name='Koncert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('dato', models.DateTimeField()),
                ('facebook', models.URLField()),
                ('billetter', models.URLField()),
                ('spillested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.spillested')),
            ],
        ),
    ]
