# Generated by Django 4.2.6 on 2024-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_koncert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frivillig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagter', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField(max_length=255)),
                ('opgaver', models.TextField()),
                ('opg_01', models.TextField()),
                ('opg_02', models.TextField()),
                ('opg_03', models.TextField()),
                ('opg_04', models.TextField()),
                ('opg_05', models.TextField(blank=True, null=True)),
                ('opg_06', models.TextField(blank=True, null=True)),
                ('opg_07', models.TextField(blank=True, null=True)),
                ('opg_08', models.TextField(blank=True, null=True)),
                ('opg_09', models.TextField(blank=True, null=True)),
                ('opg_10', models.TextField(blank=True, null=True)),
                ('opg_11', models.TextField(blank=True, null=True)),
                ('opg_12', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KoncerterSpillet',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Koncerter spillet',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.koncert',),
        ),
    ]
