# Generated by Django 4.2.6 on 2024-05-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_frivillig_koncerterspillet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frivillig',
            options={'verbose_name_plural': 'Frivillig'},
        ),
        migrations.AddField(
            model_name='koncert',
            name='band6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='koncert',
            name='band7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='koncert',
            name='band8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
